CREATE TABLE IF NOT EXISTS `tag` (
    `Id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Value` VARCHAR(255) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS `author` (
    `Id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(128) DEFAULT '',
    `Email` VARCHAR(255) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS `joke` (
    `Id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `SetUp` VARCHAR(255) DEFAULT '',
    `PunchLine` VARCHAR(255) DEFAULT '',
    `AuthorId` BIGINT,
    FOREIGN KEY (`AuthorID`) REFERENCES `author` (`Id`)
);

CREATE TABLE IF NOT EXISTS `joke_tag` (
    `Id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `JokeId` BIGINT,
    `TagId` BIGINT,
    FOREIGN KEY (`JokeId`) REFERENCES `joke` (`Id`),
    FOREIGN KEY (`TagId`) REFERENCES `tag` (`Id`)
);

CREATE TABLE IF NOT EXISTS `rating` (
    `Id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `JokeId` BIGINT,
    `Value` INT (3),
    `Comment` VARCHAR(512),
    FOREIGN KEY (`JokeId`) REFERENCES `joke` (`Id`)
);

